exclude = [
    "test/*",
    "test.py",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "venv",
]

target-version = "py310"
line-length = 125

[lint]
select = [
  "F",  # Pyflakes
  "E",
  "W",
  "C90",
  "I",
  "N",
  "UP",
  "ANN"
]
ignore = ["W191",  "ANN002", "ANN003", "UP037", "E101"]
extend-safe-fixes = ["W293", "W291", "E501"]
fixable = ["ALL"]
